[로이스] - 1주차 제출
woowacourse-study/2023-algorithm-study pull request #2
Opened 2023-06-28 13:22 UTC by TaeyeonRoyce

## 공통 문제
[백준-숫자 정사각형](https://www.acmicpc.net/problem/1051) c7bd1f6d9d381cb8d77f0c915e863deb04dcdd81

## 유형별 문제
선택한 유형: BFS, DFS 
### 관련 문제
- BFS: [백준-노드사이의 거리](https://www.acmicpc.net/problem/1240) ba115ec14757f3f402b8c2304818ab21cacbcca3
- DFS: [백준-컴백홈](https://www.acmicpc.net/problem/1189) 1758508999965e29fef09e11a935d80b41ab16f7

## 그냥 푼 문제
- 유형: 구현
  [백준-킹](https://www.acmicpc.net/problem/1063) 728bfb0bf24e70f1b7a6ab53a8dcce8d04c2a9e5

2023-06-29 07:48 UTC, 70825 requested changes

2023-06-29 07:48 UTC, 70825 commented on 1주차/로이스/Boj_1240.java
> +                }
line 50의 내용을 삭제하고, line 41 다음 줄과 line 61 다음 줄에 추가해야 할 것 같아요!
왜냐하면 큐에서 값을 꺼낼 때, visited를 업데이트하면 N값이 큰 문제의 경우에는 이미 방문한 좌표가 큐에 계속 들어가서 시간초과가 나와요
그래서 큐에 넣을 때 바로 visited를 업데이트하는게 좋습니다 👍

2023-06-29 23:59 UTC, TaeyeonRoyce commented on 1주차/로이스/Boj_1240.java
> +                }
아 그렇네요. 큐에 넣고 업데이트를 하면 큐에 겹치는(?) 다른 노드들이 들어있을 수 있네요. 감사합니다~!👍

2023-06-30 00:06 UTC, TaeyeonRoyce commented on 1주차/로이스/Boj_1240.java
> +                }
메모리도 줄고 시간도 488ms -> 410ms 로 줄었습니다!@!

2023-06-30 00:57 UTC, 70825 approved these changes

2023-07-02 05:45 UTC, merged